requires = ["tox>=4"]
env_list = ["tests", "lint", "formatter", "3.10", "3.11", "3.12"]

[env.tests]
description = "run unit tests"
deps = [
    "pytest>=8"
]
commands = [["pytest", { replace = "posargs", default = ["tests"], extend = true }]]

[env.lint]
description = "run linters"
skip_install = true
deps = ["ruff"]
commands = [
    ["ruff", "check", ".", "--fix"]
]

[env.formatter]
description = "run formatter"
skip_install = true
deps = ["ruff"]
commands = [
    ["ruff", "format", "."]
]