# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from cart_service.app.infrastructure.grpc.proto import (
    cart_service_pb2 as cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2,
)

GRPC_GENERATED_VERSION = "1.69.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in cart_service/app/infrastructure/grpc/proto/cart_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class CartServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCart = channel.unary_unary(
            "/cart.CartService/CreateCart",
            request_serializer=cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.CreateCartRequest.SerializeToString,
            response_deserializer=cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.CreateCartResponse.FromString,
            _registered_method=True,
        )
        self.RemoveCart = channel.unary_unary(
            "/cart.CartService/RemoveCart",
            request_serializer=cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.RemoveCartRequest.SerializeToString,
            response_deserializer=cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.RemoveCartResponse.FromString,
            _registered_method=True,
        )
        self.AddToCart = channel.unary_unary(
            "/cart.CartService/AddToCart",
            request_serializer=cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.AddToCartRequest.SerializeToString,
            response_deserializer=cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.AddToCartResponse.FromString,
            _registered_method=True,
        )
        self.RemoveFromCart = channel.unary_unary(
            "/cart.CartService/RemoveFromCart",
            request_serializer=cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.RemoveFromCartRequest.SerializeToString,
            response_deserializer=cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.RemoveFromCartResponse.FromString,
            _registered_method=True,
        )
        self.GetCart = channel.unary_unary(
            "/cart.CartService/GetCart",
            request_serializer=cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.GetCartRequest.SerializeToString,
            response_deserializer=cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.GetCartResponse.FromString,
            _registered_method=True,
        )


class CartServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RemoveCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AddToCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RemoveFromCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CartServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateCart": grpc.unary_unary_rpc_method_handler(
            servicer.CreateCart,
            request_deserializer=cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.CreateCartRequest.FromString,
            response_serializer=cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.CreateCartResponse.SerializeToString,
        ),
        "RemoveCart": grpc.unary_unary_rpc_method_handler(
            servicer.RemoveCart,
            request_deserializer=cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.RemoveCartRequest.FromString,
            response_serializer=cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.RemoveCartResponse.SerializeToString,
        ),
        "AddToCart": grpc.unary_unary_rpc_method_handler(
            servicer.AddToCart,
            request_deserializer=cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.AddToCartRequest.FromString,
            response_serializer=cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.AddToCartResponse.SerializeToString,
        ),
        "RemoveFromCart": grpc.unary_unary_rpc_method_handler(
            servicer.RemoveFromCart,
            request_deserializer=cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.RemoveFromCartRequest.FromString,
            response_serializer=cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.RemoveFromCartResponse.SerializeToString,
        ),
        "GetCart": grpc.unary_unary_rpc_method_handler(
            servicer.GetCart,
            request_deserializer=cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.GetCartRequest.FromString,
            response_serializer=cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.GetCartResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "cart.CartService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "cart.CartService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class CartService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCart(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cart.CartService/CreateCart",
            cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.CreateCartRequest.SerializeToString,
            cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.CreateCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RemoveCart(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cart.CartService/RemoveCart",
            cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.RemoveCartRequest.SerializeToString,
            cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.RemoveCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AddToCart(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cart.CartService/AddToCart",
            cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.AddToCartRequest.SerializeToString,
            cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.AddToCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RemoveFromCart(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cart.CartService/RemoveFromCart",
            cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.RemoveFromCartRequest.SerializeToString,
            cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.RemoveFromCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetCart(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/cart.CartService/GetCart",
            cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.GetCartRequest.SerializeToString,
            cart__service_dot_app_dot_infrastructure_dot_grpc_dot_proto_dot_cart__service__pb2.GetCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
