# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cart_service/app/infrastructure/grpc/proto/cart_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    "",
    "cart_service/app/infrastructure/grpc/proto/cart_service.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n=cart_service/app/infrastructure/grpc/proto/cart_service.proto\x12\x04\x63\x61rt"#\n\x04\x43\x61rt\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05"D\n\x08\x43\x61rtItem\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x12\n\nunit_price\x18\x03 \x01(\x02"$\n\x11\x43reateCartRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05"%\n\x12\x43reateCartResponse\x12\x0f\n\x07\x63\x61rt_id\x18\x01 \x01(\x05"$\n\x11RemoveCartRequest\x12\x0f\n\x07\x63\x61rt_id\x18\x01 \x01(\x05"%\n\x12RemoveCartResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08"]\n\x10\x41\x64\x64ToCartRequest\x12\x0f\n\x07\x63\x61rt_id\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\x05\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\x12\n\nunit_price\x18\x04 \x01(\x02"$\n\x11\x41\x64\x64ToCartResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08"<\n\x15RemoveFromCartRequest\x12\x0f\n\x07\x63\x61rt_id\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\x05")\n\x16RemoveFromCartResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08"!\n\x0eGetCartRequest\x12\x0f\n\x07\x63\x61rt_id\x18\x01 \x01(\x05"Y\n\x0fGetCartResponse\x12\x18\n\x04\x63\x61rt\x18\x01 \x01(\x0b\x32\n.cart.Cart\x12\x1d\n\x05items\x18\x02 \x03(\x0b\x32\x0e.cart.CartItem\x12\r\n\x05total\x18\x03 \x01(\x01\x32\xd2\x02\n\x0b\x43\x61rtService\x12?\n\nCreateCart\x12\x17.cart.CreateCartRequest\x1a\x18.cart.CreateCartResponse\x12?\n\nRemoveCart\x12\x17.cart.RemoveCartRequest\x1a\x18.cart.RemoveCartResponse\x12<\n\tAddToCart\x12\x16.cart.AddToCartRequest\x1a\x17.cart.AddToCartResponse\x12K\n\x0eRemoveFromCart\x12\x1b.cart.RemoveFromCartRequest\x1a\x1c.cart.RemoveFromCartResponse\x12\x36\n\x07GetCart\x12\x14.cart.GetCartRequest\x1a\x15.cart.GetCartResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR,
    "cart_service.app.infrastructure.grpc.proto.cart_service_pb2",
    _globals,
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CART"]._serialized_start = 71
    _globals["_CART"]._serialized_end = 106
    _globals["_CARTITEM"]._serialized_start = 108
    _globals["_CARTITEM"]._serialized_end = 176
    _globals["_CREATECARTREQUEST"]._serialized_start = 178
    _globals["_CREATECARTREQUEST"]._serialized_end = 214
    _globals["_CREATECARTRESPONSE"]._serialized_start = 216
    _globals["_CREATECARTRESPONSE"]._serialized_end = 253
    _globals["_REMOVECARTREQUEST"]._serialized_start = 255
    _globals["_REMOVECARTREQUEST"]._serialized_end = 291
    _globals["_REMOVECARTRESPONSE"]._serialized_start = 293
    _globals["_REMOVECARTRESPONSE"]._serialized_end = 330
    _globals["_ADDTOCARTREQUEST"]._serialized_start = 332
    _globals["_ADDTOCARTREQUEST"]._serialized_end = 425
    _globals["_ADDTOCARTRESPONSE"]._serialized_start = 427
    _globals["_ADDTOCARTRESPONSE"]._serialized_end = 463
    _globals["_REMOVEFROMCARTREQUEST"]._serialized_start = 465
    _globals["_REMOVEFROMCARTREQUEST"]._serialized_end = 525
    _globals["_REMOVEFROMCARTRESPONSE"]._serialized_start = 527
    _globals["_REMOVEFROMCARTRESPONSE"]._serialized_end = 568
    _globals["_GETCARTREQUEST"]._serialized_start = 570
    _globals["_GETCARTREQUEST"]._serialized_end = 603
    _globals["_GETCARTRESPONSE"]._serialized_start = 605
    _globals["_GETCARTRESPONSE"]._serialized_end = 694
    _globals["_CARTSERVICE"]._serialized_start = 697
    _globals["_CARTSERVICE"]._serialized_end = 1035
# @@protoc_insertion_point(module_scope)
